### ISSUE TITLE
Haswell removal

### ISSUE THREAD

**Issue by jhofweber** [IngmarStein/Monolingual#269]
I just removed Haswell resources from my Intel Mac under the presumption that it’s for machines with Haswell chips. Only after doing so did I consider the possibility that all models with ≥Haswell chips might use that code. Couldn’t find any documentation anywhere. Please shed some light. Thanks.

**Comment by IngmarStein** [comment]
Usually, a fat binary with a slice containing Haswell-optimized (x86_64h) code also contains a generic x86_64 slice so that CPUs without the Haswell feature subset can also execute it. If you remove the Haswell slice but have a CPU which provides Haswell instructions, you'll run a less optimized version of the code. On modern x86 CPUs, you'd want to keep this architecture.

**Comment by gothickitty93** [comment]
Somewhat related question, on a ≥Haswell system, when selecting the Intel 64-bit (non Haswell) option, will removal occur if it is the only version of the binary in a give App?

**Comment by gothickitty93** [comment]
> Somewhat related question, on a ≥Haswell system, when selecting the Intel 64-bit (non Haswell) option, will removal occur if it is the only version of the binary in a given App?

I tested my theory. It is NOT smart enough to delineate between the two if it is the only binary slice. (Time to restore from Time Machine...)
