### ISSUE TITLE
Monolingual doesn't actually remove anything in El Capitan

### ISSUE THREAD

**Issue by JKLStudiosInc** [IngmarStein/Monolingual#46]
It goes through all the motions and says it's removing all kinds of stuff, and reports a total of space reclaimed at the end. All just what you'd expect. But if you run it again, it starts processing all of the same items all over again as if you had just reinstalled the OS.

Something to do with the new "rootless" way El Capitan runs? Or new permissions that prevent Monolingual from doing anything? I'd lean towards the second myself. I always delete apps I will never use, and in El Capitan, you can't even remove things using Terminal with the sudo command. You're told you don't have sufficient privileges. The only way to can apps you don't want on the drive is to boot to any other drive/partition and then delete them while it's not the startup drive.

**Comment by bbbear2002** [comment]
I have tried Monolingual on El Capitan with almost everything fine except Microsoft Office 2016.

**Comment by JKLStudiosInc** [comment]
Yeah, I'm not sure what's going on there. I installed El Capitan on an erased partition so everything is clean. No matter how many times I run Monolingual, it says it's removing the same language files from the same apps over and over.

**Comment by DrWhat** [comment]
You are correct, it’s called SIP (System Integrity Protection) and it is on by default in El Capitan. To see the full list of locations that cannot be modified by root, take a look at </System/Library/Sandbox/rootless.conf> It lists all the objects protected by SIP. Monolingual cannot modify them.

You’ll notice that in addition to locations like

* /System
* /bin
* /usr
* /sbin

it also contains almost all the core OS X apps.

If you want to disable SIP, you’ll need to boot from your Recovery partition, launch Terminal, and run the <csrutil> with the command <disable>; then reboot normally. It’s not safe, but that’s the only way.

To save users time, I think Monolingual, when run on El Captain, should do a check for the status of SIP, and if it is enabled (the majority of cases), it should skip the locations listed in </System/Library/Sandbox/rootless.conf>. Otherwise it’s almost worth deleting extra languages manually, when you, say, update a third-party app.

**Comment by IngmarStein** [comment]
This was more of a cosmetic problem: Monolingual <= 1.7.1 tried to remove files protected by SIP and reported their size although the deletion failed. 1.7.2 will fix this by skipping files who have the extended attribute "com.apple.rootless" - regardless if SIP is actually active or not (these files are meant to be protected, so I'll play safe here).

**Comment by JKLStudiosInc** [comment]
Ah, I figured it had something to do with the new security features. Thanks for the info!

While you already figured out what I meant, I should clarify for others reading this topic that by not removing languages, I meant Monolingual wasn't processing OS X installed items. It still otherwise works as expected with third party apps.
