### ISSUE TITLE
Four things wrong with Monolingual, in my opinion 

### ISSUE THREAD

**Issue by lunarbase** [IngmarStein/Monolingual#65]
1. It installs a "helper" on Mac OS X. For those who hate when developers do this, this is enough to make me give up monolingual.
2. It is not working on El Capitan, even with "csrutil disable". It stops in the install "helper" phase.
3. It does not save the languages I have selected for removal, so it will not make me do 500 clicks next time.
4. it should show a resumed list by language and allow expansion. Having to click on 400 english options I don't want to remove plus the #3 bug is annoying.

Hope you guys solve that. Thanks.

**Comment by IngmarStein** [comment]
1. There are two options: have the complete Monolingual application require admin privileges (it needs those to process system files) or have a sandboxed user interface and a very small privileged helper. The second it Apple's recommended approach because it has a reduced attack surface. "Helpers" are good for security.
2. It's a bug in El Capitan. Apple has acknowledged it and the bug is still "open". See #48 
3. Just use System Preferences to manage the list. You've already filed that as #60, no need to duplicate that.
4. Almost no applications actually use English variants except the occasional en_US + en_UK combination.
5. It's not "you guys" - just me. Feel free to contribute to the open source project.
