### ISSUE TITLE
Question about SIP/rootless

### ISSUE THREAD

**Issue by ROpdebee** [IngmarStein/Monolingual#74]
Hi,

I'm gonna start off with apologizing because I can imagine you've been asked lots about rootless/SIP in the past. I know ML skips the files protected by SIP, which is obviously the way to go when SIP is enabled, but what does it do when it's disabled? It's such a waste of space having tonnes of languages installed after every OS update, but they can't be removed because of rootless, so I'm looking into disabling rootless temporarily after updating and removing the languages while it is disabled.

So, can ML check the rootless status (something like `csrutil status`) and decide whether or not to skip these files based on the result? That would help me (and possibly others) out a lot. You might even display a notice that users can disable (and re-enable!!) SIP to remove the junk after updating.

As a side note, it'd be really nice if Apple introduced App Thinning for language files so we don't have to download and install them at all. That way we could save some space on our phones as well!

Other remarks:
1. Auto-update from 1.7.2 -> 1.7.3 failed because the download URL seems to be down (404).
2. You might want to look into #62, this issue still persists and you may have missed it. Some example apps for zh-Hans & zh-Hant: Wunderlist, Skype. They seem to show up just fine in the language selection table though.

Thanks!

**Comment by IngmarStein** [comment]
That's an interesting suggestion. Currently, ML just skips all files that have the `com.apple.rootless` extended attribute - no matter if SIP is enabled or not.
Unfortunately, it seems like there is no public API to check the rootless status. csrutil uses the private API `csr_get_active_config` (https://forums.developer.apple.com/thread/16065). Since ML is not distributed on the Mac App Store, it can be used, but it's probably not a good idea to depend on this implementation detail… Any alternatives?

As for the other points:

1. Right, that was when the tar.bz2 file wasn't up, yet. Should be fixed in the meantime.
2. "xx_YY" is the old-style locale identifier - new ones look like "xx-YY". I'll just add both in the next release and document it in #62.

**Comment by ROpdebee** [comment]
I'm not an OS X developer so I don't know of any APIs but a very straightforward (and **naive**) strategy would be to try and remove a rootless protected file and if it fails because of some authorization error, conclude that rootless is enabled, otherwise it's disabled. Note that I also mentioned that this method is naive because it all depends on which information is returned from the removal operation, e.g. it could be a problem if there is no distinct error for removing rootless-protected files, or if there's no error at all.

**Comment by IngmarStein** [comment]
In a previous version, ML didn't care about SIP at all and just tried to remove all matching files. This led to the situation that users who opted to move the files to the trash, ended up with issue #63, i.e., they couldn't empty the trash anymore.
One way to solve this would be to try removing these files if the user wants to delete them, but skip them if they are to be moved to trash. In addition, ML would need to detect the correct error information, so that it doesn't spam the syslog with many error messages (which are otherwise helpful).
I'm still looking for a cleaner solution…

**Comment by ROpdebee** [comment]
From http://narkive.com/JEN7tXJR:9.358.298
> The open() API returns EPERM when you try to access something protected by SIP, but EACCES for normal permission errors. So, you could just try to write to create a file at /System/foo without root access using open(), and use the value returned by errno to determine whether SIP is enabled or not.
It's an ugly solution though. You could also try creating your own ``csr_get_active_config`` by investigating the NVRAM but then it seems better to just use the private API. You could even execute the ``csrutil status`` command and parse its output, though this could present a big problem if they ever decide to change the output format. It's up to you to decide, of course.

To clarify my earlier post, I wasn't saying that ML should try to delete every protected file, but should just maintain some kind of boolean flag that indicates whether or not rootless is enabled, its value initially being false and getting set to true whenever an error related to rootless pops up. When it's determined that rootless is enabled, ML should just skip every protected file. So you could set that flag based on the result of one of the methods I listed above before searching for language files, and remove only if ``unwanted && !(fileProtected && rootlessEnabled)``, that way you won't have to check for errors on every removal.

**Comment by ROpdebee** [comment]
Hi, any update on this? I've just installed Sierra and I'd like to remove its language files. I've tried building the source but I can't seem to get that working.

**Comment by IngmarStein** [comment]
Version 1.7.4 has a new check for SIP. Let me know if that works for you.

**Comment by ROpdebee** [comment]
I've just updated both macOS and ML and disabled rootless, good news is that the protected files are now getting removed successfully, so thanks lots for this, it saves me a few hundred MB.

Bad news is that ML now seems to completely ignore Xcode (by design?). The logs show tens if not hundreds of entries of some kind of error messages.
`CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG` (shows up for loads of other processes too) and `MacOS error: -67028`, both category `security_exception`. Might be related to the Xcode issue. I'm gonna restart back into SIP enabled mode and see if the issue persists.
