### ISSUE TITLE
Something special with /Applications/Messages.app ?

### ISSUE THREAD

**Issue by Arthur111** [IngmarStein/Monolingual#84]
After running Monolingual 1.7.3 with latest osx (10.11.4) there are a lot of xx.lproj again in /Applications/Messages.app/Contents/Resources which is not the case with iTunes for example.
There is no English.lproj but en.lproj (maybe this can help).

**Comment by ROpdebee** [comment]
Messages.app is protected by System Integrity Protection (SIP, aka rootless). If it's enabled, ML can't remove anything from this app and all other stock apps (such as Safari, Console, ...) or the /System folder, as it doesn't have the permission to do so. SIP can be (temporarily) disabled but even then ML 1.7.3 doesn't remove those files. I've filed an issue (#74) on this and it seems like @IngmarStein already implemented this for the next release, so my advice is to wait until 1.7.4, **temporarily** disable SIP and remove the language files, then enable it again.

As for why iTunes is not affected, I don't know why it isn't protected by SIP but possibly because it's a standalone app and doesn't get installed automatically when updating/installing OS X.

For when 1.7.4 gets released:

1. Reboot your Mac in Recovery Mode, by pressing `cmd (⌘)` + `R` at boot.
2. Navigate to Utilities > Terminal when the recovery menu pops up.
3. Enter `csrutil disable; reboot` into the terminal and hit enter, this will disable SIP and reboot the Mac.
4. When it's rebooted, fire up ML and remove the language files.
5. When ML is finished removing languages, reboot back into recovery mode and enter `csrutil enable; reboot` to enable SIP again.

I'll stress again that this will not work on the current version of ML and will only succeed when a new version gets released that supports removing protected language files, probably 1.7.4. Also note that this may not work if you opted to move the files to the trash instead of directly removing them.

Hope this helps.

**Comment by Arthur111** [comment]
Ah .. SIP ..
Thank you for the explanation.
Which part of SIP is concerned ?

fs  ?

Like this : 

csrutil disable
csrutil enable --without fs 
reboot

https://forums.developer.apple.com/thread/17452

**Comment by ROpdebee** [comment]
I would guess it's indeed fs that's concerned, however I don't recommend leaving the filesystem protection off forever (if that's what you intend to do). I can't confirm that it'll work if you just disable the fs protections either.

**Comment by Arthur111** [comment]
Ok.
Thank you
