### ISSUE TITLE
Monolingual 1.7.4 removes .lproj files from my language/region

### ISSUE THREAD

**Issue by unsureone** [IngmarStein/Monolingual#98]
Running Sierra, in Monolingual 1.7.3, the app would remove "en-US.lproj" files/folders on the drive if "English" and "English (United States)" were unchecked in Monolingual and if "English - United States" was selected in the Language & Region preference pane.

Running Sierra, in Monolingual 1.7.4, the app also removes "en_US.lproj" files/folders using the above settings.

In both cases, it leaves "English.lproj" files/folders alone.

The only way to prevent "en-US.lproj" and "en_US.lproj" resources from being removed is to uncheck "English (United States, Computer)" in Monolingual, but then it becomes checked again if you close and reopen Monolingual.

Are these specific .lproj files/folders (for my language and region) not needed by apps to display and operate properly? (In the case of TurboTax, for example, there is no "English.lproj" folder--there's only an "en_US.lproj" folder present, so there's no applicable .lproj file left when 1.7.4 removes the "en_US.lproj" file/folder.)

Thanks,
David

**Comment by IngmarStein** [comment]
Thanks for the report, the issue will be fixed in 1.7.5.

The locale "English (United States, Computer)" has the identifier "en_US_POSIX" and that was wrongly mapped to to "en_US.lproj" and "en-US.lproj". en_US_POSIX should not be used for user-facing localization files and I'm not aware of any app doing that.

As far as en_US.lproj is concerned: very few apps actually discern between en_US and en_GB and of those which do, many have English.lproj (or en.lproj) in addition. TurboTax seems to be an exception and I would reinstall the program after 1.7.5 is out. Many apps use the English strings as localization keys which is why you might not see any effect.
